//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTOMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public int DNI_CLIENTE { get; set; }
        public string NOM_CLIENTE { get; set; }
        public string DIR_CLIENTE { get; set; }
        public Nullable<int> TEL_CLIENTE { get; set; }
    }
}
